spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: cliftons04
    password: Cliftons2018
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
